package com.techm.bm.om.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BMTest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String one;

	public BMTest() {
	}

	public java.lang.String getOne() {
		return this.one;
	}

	public void setOne(java.lang.String one) {
		this.one = one;
	}

	public BMTest(java.lang.String one) {
		this.one = one;
	}

}