package com.techm.bm.om.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Branch implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Branch() {
    }




}