package com.techm.bm.om.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Branch implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String b1;

	public Branch() {
	}

	public java.lang.String getB1() {
		return this.b1;
	}

	public void setB1(java.lang.String b1) {
		this.b1 = b1;
	}

	public Branch(java.lang.String b1) {
		this.b1 = b1;
	}

}