package com.om.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String one;

	public Test() {
	}

	public java.lang.String getOne() {
		return this.one;
	}

	public void setOne(java.lang.String one) {
		this.one = one;
	}

	public Test(java.lang.String one) {
		this.one = one;
	}

}